In [226]:
import numpy as np
import pandas as pd

 # คณิศร โอภิธากร 660710697

In [227]:
std = pd.read_csv("student.csv")

In [228]:
std

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2023-12-19
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-01-09
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-02-03
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-14
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-15
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-02-03
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-24
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2023-12-29
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2023-12-20
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-05
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-19
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-01-24
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-13
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-12
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2023-12-22
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-12
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-14
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-06
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-03
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-10

In [229]:
std.isnull().sum()

รหัสนักศึกษา               0
ชื่อ                       1
อายุ                       3
เพศ                        2
คณะ                        2
GPA                        2
ส่วนสูง_cm                 1
น้ำหนัก_kg                 2
ชั่วโมงเรียน_ต่อสัปดาห์    2
วันที่ลงทะเบียน            0
dtype: int64

In [230]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์', 'Sci']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts' , 'Liberal Arts']:
        return 'ศิลปศาสตร์'
    elif name in ['วิศวะ', 'Engineering', 'วิศวฯ' , 'วิศวกรรม']:
        return 'วิศวกรรมศาสตร์'
    else:
        return name
std['คณะ'] = std['คณะ'].apply(standardize_faculty)

In [231]:
def standardize_gender(gender):
    if gender in ['Male', 'M' , 'ช' ]:
        return 'ชาย'
    elif gender in ['Female', 'F' , 'ญ' ]:
        return 'หญิง'
    else:
        return gender
std['เพศ'] = std['เพศ'].apply(standardize_gender)

In [232]:
std.loc[(std['GPA'] < 1) | (std['GPA'] > 4), 'GPA'] = np.nan

Q1 = std['อายุ'].quantile(0.25)
Q3 = std['อายุ'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(lower_bound)
print(upper_bound)
std.loc[(std['อายุ'] < lower_bound) | (std['อายุ'] > upper_bound) ,'อายุ'] = np.nan

17.0
25.0

In [233]:
mean_gpa = std['GPA'].mean()
std['GPA'] = std['GPA'].fillna(mean_gpa.round(2))

In [234]:
std

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2023-12-19
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-01-09
2,64003,NaN,NaN,ชาย,วิทยาศาสตร์,3.67,175.0,NaN,25.0,2024-02-03
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,3.43,168.0,70.0,10.0,2024-01-14
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-15
5,64006,กานต์,NaN,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-02-03
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,3.43,158.0,48.0,35.0,2024-01-24
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2023-12-29
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2023-12-20
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-05
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-19
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.43,171.0,NaN,16.0,2024-01-24
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2024-01-13
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-12
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2023-12-22
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-12
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-14
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-06
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,3.43,174.0,76.0,NaN,2024-01-03
19,64020,ลัดดา,22.0,NaN,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-10

In [235]:
std.isnull().sum()

รหัสนักศึกษา               0
ชื่อ                       1
อายุ                       4
เพศ                        2
คณะ                        2
GPA                        0
ส่วนสูง_cm                 1
น้ำหนัก_kg                 2
ชั่วโมงเรียน_ต่อสัปดาห์    2
วันที่ลงทะเบียน            0
dtype: int64

In [236]:
std['ชื่อ'].fillna('ไม่ระบุ', inplace=True)
std['อายุ'].fillna(std['อายุ'].mode()[0], inplace=True)
std['เพศ'].fillna(std['เพศ'].mode()[0], inplace=True)
std['คณะ'].fillna(std['คณะ'].mode()[0], inplace=True)
std['ส่วนสูง_cm'].fillna(std['ส่วนสูง_cm'].mode()[0], inplace=True)
std['น้ำหนัก_kg'].fillna(std['น้ำหนัก_kg'].mode()[0], inplace=True)
std['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(std['ชั่วโมงเรียน_ต่อสัปดาห์'].mode()[0], inplace=True)

/tmp/ipython-input-1890579708.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  std['ชื่อ'].fillna('ไม่ระบุ', inplace=True)
/tmp/ipython-input-1890579708.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  std['อายุ'].fillna(std['อายุ'].mode()[0], inplace=True)
/tmp/ipython-input-1890579708.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  std['เพศ'].fillna(std['เพศ'].mode()[0], inplace=True)
/tmp/ipython-input-1890579708.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  std['คณะ'].fillna(std['คณะ'].mode()[0], inplace=True)
/tmp/ipython-input-1890579708.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  std['ส่วนสูง_cm'].fillna(std['ส่วนสูง_cm'].mode()[0], inplace=True)
/tmp/ipython-input-1890579708.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  std['น้ำหนัก_kg'].fillna(std['น้ำหนัก_kg'].mode()[0], inplace=True)
/tmp/ipython-input-1890579708.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  std['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(std['ชั่วโมงเรียน_ต่อสัปดาห์'].mode()[0], inplace=True)

In [237]:
std

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2023-12-19
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-01-09
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.67,175.0,48.0,25.0,2024-02-03
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,3.43,168.0,70.0,10.0,2024-01-14
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-15
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-02-03
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,3.43,158.0,48.0,35.0,2024-01-24
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2023-12-29
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2023-12-20
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-05
10,64011,ธีระ,21.0,ชาย,วิทยาศาสตร์,3.78,168.0,68.0,10.0,2024-01-19
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.43,171.0,48.0,16.0,2024-01-24
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2024-01-13
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-12
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2023-12-22
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-12
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-14
17,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-06
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.43,174.0,76.0,10.0,2024-01-03
19,64020,ลัดดา,22.0,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-10

In [238]:

# ทำ One-Hot Encoding
data_encoded = pd.get_dummies(std, columns=['คณะ'])

In [239]:
data_encoded

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,คณะ_วิทยาศาสตร์,คณะ_วิศวกรรมศาสตร์,คณะ_ศิลปศาสตร์
0,64001,สมชาย,20.0,ชาย,3.21,170.0,65.0,15.0,2023-12-19,True,False,False
1,64002,สมหญิง,21.0,หญิง,3.45,165.0,58.0,20.0,2024-01-09,True,False,False
2,64003,ไม่ระบุ,21.0,ชาย,3.67,175.0,48.0,25.0,2024-02-03,True,False,False
3,64004,สมศักดิ์,22.0,ชาย,3.43,168.0,70.0,10.0,2024-01-14,True,False,False
4,64005,สมใจ,19.0,หญิง,3.89,160.0,52.0,30.0,2024-01-15,False,True,False
5,64006,กานต์,21.0,ชาย,3.12,172.0,75.0,12.0,2024-02-03,False,True,False
6,64007,กิตติ,21.0,หญิง,3.43,158.0,48.0,35.0,2024-01-24,False,True,False
7,64008,จิรา,20.0,หญิง,2.98,180.0,82.0,18.0,2023-12-29,False,False,True
8,64009,ชนาธิป,23.0,ชาย,3.34,163.0,55.0,22.0,2023-12-20,False,False,True
9,64010,ดารา,21.0,หญิง,3.56,167.0,60.0,28.0,2024-01-05,False,False,True
10,64011,ธีระ,21.0,ชาย,3.78,168.0,68.0,10.0,2024-01-19,True,False,False
11,64012,นภา,22.0,ชาย,3.43,171.0,48.0,16.0,2024-01-24,True,False,False
12,64013,บุญมี,20.0,หญิง,3.23,169.0,72.0,24.0,2024-01-13,False,True,False
13,64014,ปรีชา,21.0,ชาย,3.45,164.0,54.0,19.0,2024-01-12,False,False,True
14,64015,พิมพ์,22.0,หญิง,3.67,162.0,56.0,26.0,2023-12-22,True,False,False
15,64016,ภูมิ,19.0,ชาย,3.89,173.0,78.0,14.0,2024-01-12,True,False,False
16,64017,มานี,20.0,หญิง,3.01,166.0,62.0,21.0,2024-01-14,False,True,False
17,64018,ยุพา,21.0,หญิง,3.23,161.0,50.0,27.0,2024-01-06,True,False,False
18,64019,รัตนา,21.0,ชาย,3.43,174.0,76.0,10.0,2024-01-03,False,False,True
19,64020,ลัดดา,22.0,ชาย,3.45,168.0,64.0,23.0,2024-01-10,True,False,False

In [240]:
# สร้าง BMI
std['BMI'] = std['น้ำหนัก_kg'] / (std['ส่วนสูง_cm']/100)**2
std['สุขภาพ'] = pd.cut(std['BMI'], bins=[0, 18.5, 25, 30, 100],labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

In [241]:
std

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,BMI,สุขภาพ
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2023-12-19,22.491349,ปกติ
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0,2024-01-09,21.303949,ปกติ
2,64003,ไม่ระบุ,21.0,ชาย,วิทยาศาสตร์,3.67,175.0,48.0,25.0,2024-02-03,15.673469,ผอม
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,3.43,168.0,70.0,10.0,2024-01-14,24.801587,ปกติ
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0,2024-01-15,20.312500,ปกติ
5,64006,กานต์,21.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0,2024-02-03,25.351541,อ้วน
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,3.43,158.0,48.0,35.0,2024-01-24,19.227688,ปกติ
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2023-12-29,25.308642,อ้วน
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0,2023-12-20,20.700817,ปกติ
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0,2024-01-05,21.513859,ปกติ
10,64011,ธีระ,21.0,ชาย,วิทยาศาสตร์,3.78,168.0,68.0,10.0,2024-01-19,24.092971,ปกติ
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.43,171.0,48.0,16.0,2024-01-24,16.415307,ผอม
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0,2024-01-13,25.209201,อ้วน
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0,2024-01-12,20.077335,ปกติ
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0,2023-12-22,21.338211,ปกติ
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-12,26.061679,อ้วน
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-14,22.499637,ปกติ
17,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.23,161.0,50.0,27.0,2024-01-06,19.289379,ปกติ
18,64019,รัตนา,21.0,ชาย,ศิลปศาสตร์,3.43,174.0,76.0,10.0,2024-01-03,25.102391,อ้วน
19,64020,ลัดดา,22.0,ชาย,วิทยาศาสตร์,3.45,168.0,64.0,23.0,2024-01-10,22.675737,ปกติ